version: '3.8'

services:
  db:
    image: postgres:15 # 使用一个明确的 PostgreSQL 版本
    container_name: recipe_planner_db_local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
      POSTGRES_DB: recipe_planner_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user -d recipe_planner_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local