import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function seedIngredients() {
  console.log("Seeding ingredients data...")

  try {
    // 检查表是否存在
    try {
      await prisma.$queryRaw`SELECT * FROM "Ingredient" LIMIT 1`
      console.log("Ingredient table exists")
    } catch (error) {
      console.error("Ingredient table does not exist:", error)
      console.log("Please run migrations first")
      return
    }

    // 添加常见食材的营养数据
    const ingredients = [
      {
        id: "clr1",
        name: "鸡胸肉",
        category: "肉类海鲜",
        calories: 165,
        protein: 31,
        fat: 3.6,
        carbs: 0,
        fiber: 0,
        sugar: 0,
        sodium: 74,
      },
      {
        id: "clr2",
        name: "三文鱼",
        category: "肉类海鲜",
        calories: 208,
        protein: 20,
        fat: 13,
        carbs: 0,
        fiber: 0,
        sugar: 0,
        sodium: 59,
      },
      {
        id: "clr3",
        name: "牛肉(瘦)",
        category: "肉类海鲜",
        calories: 250,
        protein: 26,
        fat: 17,
        carbs: 0,
        fiber: 0,
        sugar: 0,
        sodium: 72,
      },
      {
        id: "clr4",
        name: "猪肉(瘦)",
        category: "肉类海鲜",
        calories: 242,
        protein: 26,
        fat: 14,
        carbs: 0,
        fiber: 0,
        sugar: 0,
        sodium: 62,
      },
      {
        id: "clr5",
        name: "鸡蛋",
        category: "乳制品蛋类",
        calories: 155,
        protein: 13,
        fat: 11,
        carbs: 1.1,
        fiber: 0,
        sugar: 1.1,
        sodium: 124,
      },
      {
        id: "clr6",
        name: "豆腐",
        category: "谷物豆类",
        calories: 76,
        protein: 8,
        fat: 4.2,
        carbs: 1.9,
        fiber: 0.3,
        sugar: 0.7,
        sodium: 7,
      },
      {
        id: "clr7",
        name: "米饭(熟)",
        category: "谷物豆类",
        calories: 130,
        protein: 2.7,
        fat: 0.3,
        carbs: 28,
        fiber: 0.4,
        sugar: 0.1,
        sodium: 1,
      },
      {
        id: "clr8",
        name: "面条(熟)",
        category: "谷物豆类",
        calories: 138,
        protein: 5.0,
        fat: 2.1,
        carbs: 25,
        fiber: 1.2,
        sugar: 0.6,
        sodium: 2,
      },
      {
        id: "clr9",
        name: "土豆",
        category: "蔬菜水果",
        calories: 77,
        protein: 2.0,
        fat: 0.1,
        carbs: 17,
        fiber: 2.2,
        sugar: 0.8,
        sodium: 6,
      },
      {
        id: "clr10",
        name: "西兰花",
        category: "蔬菜水果",
        calories: 34,
        protein: 2.8,
        fat: 0.4,
        carbs: 6.6,
        fiber: 2.6,
        sugar: 1.7,
        sodium: 33,
      },
      {
        id: "clr11",
        name: "胡萝卜",
        category: "蔬菜水果",
        calories: 41,
        protein: 0.9,
        fat: 0.2,
        carbs: 9.6,
        fiber: 2.8,
        sugar: 4.7,
        sodium: 69,
      },
      {
        id: "clr12",
        name: "西红柿",
        category: "蔬菜水果",
        calories: 18,
        protein: 0.9,
        fat: 0.2,
        carbs: 3.9,
        fiber: 1.2,
        sugar: 2.6,
        sodium: 5,
      },
      {
        id: "clr13",
        name: "黄瓜",
        category: "蔬菜水果",
        calories: 15,
        protein: 0.7,
        fat: 0.1,
        carbs: 3.6,
        fiber: 0.5,
        sugar: 1.7,
        sodium: 2,
      },
      {
        id: "clr14",
        name: "菠菜",
        category: "蔬菜水果",
        calories: 23,
        protein: 2.9,
        fat: 0.4,
        carbs: 3.6,
        fiber: 2.2,
        sugar: 0.4,
        sodium: 79,
      },
      {
        id: "clr15",
        name: "苹果",
        category: "蔬菜水果",
        calories: 52,
        protein: 0.3,
        fat: 0.2,
        carbs: 14,
        fiber: 2.4,
        sugar: 10.3,
        sodium: 1,
      },
      {
        id: "clr16",
        name: "香蕉",
        category: "蔬菜水果",
        calories: 89,
        protein: 1.1,
        fat: 0.3,
        carbs: 23,
        fiber: 2.6,
        sugar: 12.2,
        sodium: 1,
      },
      {
        id: "clr17",
        name: "牛奶",
        category: "乳制品蛋类",
        calories: 42,
        protein: 3.4,
        fat: 1.0,
        carbs: 5.0,
        fiber: 0,
        sugar: 5.0,
        sodium: 44,
      },
      {
        id: "clr18",
        name: "酸奶",
        category: "乳制品蛋类",
        calories: 59,
        protein: 3.5,
        fat: 3.3,
        carbs: 4.7,
        fiber: 0,
        sugar: 4.7,
        sodium: 46,
      },
      {
        id: "clr19",
        name: "奶酪",
        category: "乳制品蛋类",
        calories: 402,
        protein: 25,
        fat: 33,
        carbs: 1.3,
        fiber: 0,
        sugar: 0.9,
        sodium: 621,
      },
      {
        id: "clr20",
        name: "橄榄油",
        category: "调味品干货",
        calories: 884,
        protein: 0,
        fat: 100,
        carbs: 0,
        fiber: 0,
        sugar: 0,
        sodium: 2,
      },
      {
        id: "clr21",
        name: "大米(生)",
        category: "谷物豆类",
        calories: 365,
        protein: 7.1,
        fat: 0.7,
        carbs: 80,
        fiber: 1.3,
        sugar: 0.1,
        sodium: 5,
      },
      {
        id: "clr22",
        name: "面粉",
        category: "谷物豆类",
        calories: 364,
        protein: 10.3,
        fat: 1.0,
        carbs: 76,
        fiber: 2.7,
        sugar: 0.3,
        sodium: 2,
      },
      {
        id: "clr23",
        name: "糖",
        category: "调味品干货",
        calories: 387,
        protein: 0,
        fat: 0,
        carbs: 100,
        fiber: 0,
        sugar: 100,
        sodium: 1,
      },
      {
        id: "clr24",
        name: "盐",
        category: "调味品干货",
        calories: 0,
        protein: 0,
        fat: 0,
        carbs: 0,
        fiber: 0,
        sugar: 0,
        sodium: 38758,
      },
      {
        id: "clr25",
        name: "黑胡椒",
        category: "调味品干货",
        calories: 251,
        protein: 10.4,
        fat: 3.3,
        carbs: 64,
        fiber: 25.3,
        sugar: 0.6,
        sodium: 20,
      },
    ]

    // 使用事务批量插入数据
    await prisma.$transaction(
      ingredients.map((ingredient) =>
        prisma.ingredient.upsert({
          where: { name: ingredient.name },
          update: ingredient,
          create: {
            ...ingredient,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        }),
      ),
    )

    console.log(`Successfully seeded ${ingredients.length} ingredients`)
  } catch (error) {
    console.error("Error seeding ingredients:", error)
    throw error
  } finally {
    await prisma.$disconnect()
  }
}

seedIngredients()
